version: '3'
services:
  postgres-db:
    container_name: crud-objetos
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: crud-objetos
